#!/command/with-contenv sh

export WORKER_PROCESSES=$(nproc)
export WORKER_CONNECTIONS=$(expr $(ulimit -n) / $WORKER_PROCESSES)

envsubst '
$MAILROOM_HOST
$MAILROOM_SRV
$COURIER_HOST
$COURIER_SRV
$WORKER_PROCESSES
$WORKER_CONNECTIONS
' </etc/nginx/templates/nginx.conf >/etc/nginx/nginx.conf

nginx
