#!/command/with-contenv sh

cd /var/www

if test "$DEBUG" = true; then
    LOG_LEVEL="debug"
else
    LOG_LEVEL="warn"
fi

# https://docs.gunicorn.org/en/latest/design.html#how-many-workers
WORKERS=$(((2 * $(nproc)) + 1))

gunicorn ureport.wsgi \
    --bind "unix:///run/gunicorn.sock" \
    --log-level $LOG_LEVEL \
    --worker-class gevent \
    --workers $WORKERS \
    --timeout 60
