#!/command/with-contenv sh

cd /var/www

if test "$DEBUG" = true; then
    LOG_LEVEL="debug"
else
    LOG_LEVEL="warning"
fi

if test "$RUN_CELERY_BEAT" = true; then
    celery -A ureport beat \
        --loglevel $LOG_LEVEL
else
    celery -A ureport worker \
        --uid nobody \
        --loglevel $LOG_LEVEL
fi
